services:
  chromadb:
    image: ${CHROMADB_FINAL_IMAGE}
    networks:
      - chatbot_net
    restart: unless-stopped 

  rag_cisuc:
    build:
      context: ./RAG_CISUC
    env_file:
      - ./config/docker_settings.env
      - .env
    networks:
      - chatbot_net
    depends_on:             
      - chromadb
    restart: unless-stopped 

  orchestrator:
    build:
      context: ./Orchestrator
    ports:
      - "${ORCHESTRATOR_HOST_PORT:?ORCHESTRATOR_HOST_PORT required}:8002"
    env_file:
      - ./config/docker_settings.env
      - .env
    networks:
      - chatbot_net
    depends_on:              # Adicionado
      - rag_cisuc
    restart: unless-stopped 

  gui:
    build:
      context: ./GUI
      args:
        VITE_ORCHESTRATOR_API_ENDPOINT: ${VITE_ORCHESTRATOR_API_ENDPOINT:?endpoint required}
    ports:
      - "${GUI_HOST_PORT:?GUI_HOST_PORT required}:80"
    depends_on:
      - orchestrator
    networks:
      - chatbot_net
    restart: unless-stopped

networks:
  chatbot_net:
    driver: bridge