services:
  gui:
    build: !reset null
    ports: !reset []

    networks:
      - chatbot_net
      - preview_proxy

    labels:
      - traefik.enable=true
      - traefik.docker.network=preview_proxy

      - traefik.http.routers.gui-${PREVIEW_ID:?PREVIEW_ID must be defined}.rule=PathPrefix(`/preview/${PREVIEW_ID}/`)
      - traefik.http.routers.gui-${PREVIEW_ID}.entrypoints=web
      - traefik.http.routers.gui-${PREVIEW_ID}.middlewares=gui-strip-${PREVIEW_ID}
      - traefik.http.routers.gui-${PREVIEW_ID}.service=gui-${PREVIEW_ID}

      - traefik.http.middlewares.gui-strip-${PREVIEW_ID}.stripprefix.prefixes=/preview/${PREVIEW_ID}

      - traefik.http.services.gui-${PREVIEW_ID}.loadbalancer.server.port=80

  orchestrator:
    build: !reset null
    ports: !reset []

    networks:
      - chatbot_net
      - preview_proxy

    labels:
      - traefik.enable=true
      - traefik.docker.network=preview_proxy

      - traefik.http.routers.chat-${PREVIEW_ID}.rule=PathPrefix(`/preview/${PREVIEW_ID}/chat`)
      - traefik.http.routers.chat-${PREVIEW_ID}.priority=100
      - traefik.http.routers.chat-${PREVIEW_ID}.entrypoints=web
      - traefik.http.routers.chat-${PREVIEW_ID}.middlewares=chat-strip-${PREVIEW_ID}
      - traefik.http.routers.chat-${PREVIEW_ID}.service=chat-${PREVIEW_ID}

      - traefik.http.middlewares.chat-strip-${PREVIEW_ID}.stripprefix.prefixes=/preview/${PREVIEW_ID}

      - traefik.http.services.chat-${PREVIEW_ID}.loadbalancer.server.port=8002

  rag_cisuc:
    build: !reset null

networks:
  chatbot_net:

  preview_proxy:
    external: true