stages:
  preprocessing:
    cmd: ./scripts/run-preprocessing-data.sh
    deps:
      - preprocessing
      - scripts/run-preprocessing-data.sh
      - scripts/run-ingestion.sh
      - scripts/run-enhancement.sh
      - scripts/run-embeddings.sh
      - config/chatbot-common.env
      - config/preprocessing.env
    outs:
      - .local/raw
      - .local/enriched
      - .local/chroma